### ISSUE TITLE
Get list of all Phonon DAO owned domains

### ISSUE THREAD

**Issue by italianst4** [PhononDAO/Content-and-Media#4]
We need to get a list of all Phonon DAO owned domains and determine which one we want to use going forward as the official domain of Phonon.

**Comment by 0xRake** [comment]
Besides phonon.network, we've got:

- phonon.xyz   
- phonon.fyi
- phonon.dev
- phonon.app
- phonon.visit (handshake)
- phonon.buzz
- phonon.cash  
- phonon.dao   (unstoppable)

**Comment by italianst4** [comment]
@0xRake Thanks for sharing this.

I'm a fan of phonon.xyz as the core root domain.

I'll get some feedback from others to see if they like the new core domain.

Thoughts?

**Comment by 0xRake** [comment]
IMO, they could all serve a purpose.
I'm partial to either .cash || .app

**Comment by italianst4** [comment]
For sure, I think there could be purpose for each, but for simplicity sake, we'll consolidate and funnel them all to an official domain. We can always spin one out in the future.

Per our DAO call Wednesday, it was a unanimous decision to go with phonon.xyz.

I have a plan for making these changes, which will be shared soon.
